version: "3"
services:
  app:
    container_name: php_dry_website_app
    build:
      context: ./infrastructure/
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
  web:
    container_name: php_dry_website_web
    build:
      context: ./infrastructure/
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
  static_site:
    container_name: php_dry_website_static_site
    build:
      context: ./infrastructure/
      dockerfile: static_site.dockerfile
    working_dir: /var/www
    volumes:
      - ./builds/latest:/var/www
    ports:
      - "8081:80"
