version: "3"
services:
  app:
    container_name: php_dry_website_app
    privileged: true
    build:
      context: ./infrastructure/
      dockerfile: app.dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    working_dir: /var/www
    volumes:
      - ./:/var/www
  web:
    container_name: php_dry_website_web
    privileged: true
    build:
      context: ./infrastructure/
      dockerfile: web.dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
  static_site:
    container_name: php_dry_website_static_site
    build:
      context: ./infrastructure/
      dockerfile: static_site.dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    working_dir: /var/www
    volumes:
      - ./builds/latest:/var/www
    ports:
      - "8081:80"
  mkdocs:
    container_name: mkdocs
    image: polinux/mkdocs:1.2.3
    restart: always
    ports:
      - "8000:8000"
    environment:
      LIVE_RELOAD_SUPPORT: 'true'
      ADD_MODULES: 'fontawesome-markdown mkdocs-git-revision-date-localized-plugin mkdocs-material'
      FAST_MODE: 'true'
      DOCS_DIRECTORY: '/mkdocs'
    volumes:
      - ./builds:/builds
      - ./mkdocs:/mkdocs
