on:
  repository_dispatch:
    types: [deploy_website]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: Test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
